controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

employee_index:
  path: /employee
  controller: App\Controller\EmployeeController::index
  methods: GET
